// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type BrandTableRow = {
    id: string;
    name: string;
    description: string;
    product: { nodes: ProductTableRow[] };
  };

  type CategoryTableRow = {
    id: string;
    name: string;
    description: string;
    product1: { nodes: Product1TableRow[] };
    productsCount: number;
  };

  type BasketTableRow = {
    id: string;
    name: string;
    idMembar: { nodes: IdMembarTableRow[] };
    idProduct: { nodes: IdProductTableRow[] };
    totalHari: number;
    ongkir: number;
    allTotal: number;
    totalHargaSewa: number;
    member2: { nodes: Member2TableRow[] };
  };

  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    password: string;
    basket: { nodes: BasketTableRow[] };
    alamat: string;
    kodePoss: number;
    product3: { nodes: Product3TableRow[] };
    basketAktif: BasketAktifTableRow;
  };

  type ProductTableRow = {
    id: string;
    name: string;
    description: string;
    brand: { nodes: BrandTableRow[] };
    category: CategoryTableRow;
    image: string;
    startDate: Date;
    endDate: Date;
    nameCategory: string;
    address: string;
    price: number;
    basket1: { nodes: Basket1TableRow[] };
    merchant: { nodes: MerchantTableRow[] };
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
      alamat: string;
      kodePoss: number;
      basketAktif: BasketAktifTableRow;
    };
    write: {
      email: string;
      password: string;
      alamat: string;
      kodePoss: number;
      basketAktif: string[];
    };
    params: {};
    actions: {};
  };

  type AllProductViewRow = {
    read: {
      id: string;
      name: string;
      brand: { nodes: BrandTableRow[] };
      category: CategoryTableRow;
      image: string;
      startDate: Date;
      endDate: Date;
      description: string;
      nameCategory: string;
      address: string;
      price: number;
      merchant: { nodes: MerchantTableRow[] };
    };
    write: {
      name: string;
      brand: string[];
      category: string[];
      image: string;
      startDate: Date;
      endDate: Date;
      description: string;
      nameCategory: string;
      address: string;
      price: number;
      merchant: string[];
    };
    params: {};
    actions: {};
  };

  type AllBrandViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
    };
    write: {
      name: string;
      description: string;
    };
    params: {};
    actions: {};
  };

  type AllCategoryViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      productsCount: number;
    };
    write: {
      name: string;
      description: string;
    };
    params: {};
    actions: {};
  };

  type AllBasketViewRow = {
    read: {
      id: string;
      name: string;
      idMembar: { nodes: IdMembarTableRow[] };
      idProduct: { nodes: IdProductTableRow[] };
      totalHari: number;
      ongkir: number;
      allTotal: number;
      totalHargaSewa: number;
    };
    write: {
      name: string;
      idMembar: string[];
      idProduct: string[];
      totalHari: number;
      ongkir: number;
      allTotal: number;
      totalHargaSewa: number;
    };
    params: {};
    actions: {};
  };

  type ProjectSchema = {
    allMember: AllMemberViewRow;
    allProduct: AllProductViewRow;
    allBrand: AllBrandViewRow;
    allCategory: AllCategoryViewRow;
    allBasket: AllBasketViewRow;
  };
}
